// <auto-generated />
using League.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace League.Migrations
{
    [DbContext(typeof(LeagueContext))]
    partial class LeagueContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("League.Models.Cake", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Calories")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImgURL")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ingredients")
                        .HasColumnType("TEXT");

                    b.Property<string>("Modal")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Prices")
                        .HasColumnType("REAL");

                    b.Property<double>("Rating")
                        .HasColumnType("REAL");

                    b.HasKey("ID");

                    b.ToTable("Cake", (string)null);
                });

            modelBuilder.Entity("League.Models.Drink", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Calories")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImgURL")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ingredients")
                        .HasColumnType("TEXT");

                    b.Property<string>("Modal")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Prices")
                        .HasColumnType("REAL");

                    b.Property<double>("Rating")
                        .HasColumnType("REAL");

                    b.HasKey("ID");

                    b.ToTable("Drink", (string)null);
                });

            modelBuilder.Entity("League.Models.FastFood", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Calories")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImgURL")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ingredients")
                        .HasColumnType("TEXT");

                    b.Property<string>("Modal")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Prices")
                        .HasColumnType("REAL");

                    b.Property<double>("Rating")
                        .HasColumnType("REAL");

                    b.HasKey("ID");

                    b.ToTable("FastFood", (string)null);
                });

            modelBuilder.Entity("League.Models.Food", b =>
                {
                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<int>("cakeID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("drinkID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("fastFoodID")
                        .HasColumnType("INTEGER");

                    b.HasIndex("cakeID");

                    b.HasIndex("drinkID");

                    b.HasIndex("fastFoodID");

                    b.ToTable("Food", (string)null);
                });

            modelBuilder.Entity("League.Models.Food", b =>
                {
                    b.HasOne("League.Models.Cake", "cake")
                        .WithMany()
                        .HasForeignKey("cakeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("League.Models.Drink", "drink")
                        .WithMany()
                        .HasForeignKey("drinkID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("League.Models.FastFood", "fastFood")
                        .WithMany()
                        .HasForeignKey("fastFoodID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("cake");

                    b.Navigation("drink");

                    b.Navigation("fastFood");
                });
#pragma warning restore 612, 618
        }
    }
}
